### ISSUE TITLE
Memory leak with Map

### ISSUE THREAD

**Issue by aferust** [AuburnSounds/Dplug#603] opened 2021-11-09 18:00 UTC
The following code causes 40040  bytes of the leak. I mostly used drmemory. But Valgrind yields a similar result too. Maybe, I am wrong but, I somehow detected that while the number of the mallocNew calls for RBNode* is 1001, and the number of the destroyFree calls is 1000 at the end of the scope.

```d
import dplug.core;

// drmemory test.exe -light -count_leaks

 int main() @nogc nothrow
{
    
    import core.stdc.stdio;

    Map!(int, int) aa0;

    foreach (i; 0..1000){
        aa0[i] = i;
    }

    foreach (i; 0..1000){
        printf("%d \n", i);
        aa0.remove(i);
        
    }
    
    // aa0.clearContents(); // the same leak with this also.

    return 0;
}


```

**Comment by p0nce** [comment] 2021-11-09 18:52
Hi @aferust thanks for the report!

**Comment by p0nce** [comment] 2021-11-09 23:36
I don't think Map this is the leak you are searching.

`clearContents()` does not deallocate `_rbt` itself. If you close the scope and measure allocations everything is returned.
Map is lazy-initialized in order not to use class, but an empty Map is still one allocation.

```
import dplug.core;


 int main() @nogc nothrow
{
    
    import core.stdc.stdio;
    {
        Map!(int, int) aa0;
        foreach (i; 0..1000){
            aa0[i] = i;
        }

        foreach (i; 0..1000){
            printf("%d \n", i);
            aa0.remove(i);        
        }
    
        aa0.clearContents();
    } // aa0 destroyed here. After this scope, number of destroyFree and mallocNew is matched
    return 0;
}
```

**Comment by aferust** [comment] 2021-11-10 06:56
I am creating a betterC port of the RedBlackTree and Ma.p I used struct for RBtree instead of class. It looks like I forgot to add an extra destroyFree(_end) for the last node [here](https://github.com/aferust/bcrbtree/blob/main/source/bcrbtree/bcrbtree.d#L717).  Now there is no leak reported with my port.  However, drmemory still reports leaks with dplug. I don't know [this one](https://github.com/AuburnSounds/Dplug/blob/master/graphics/dplug/graphics/font.d#L325) is related also.

**Comment by p0nce** [comment] 2021-11-10 10:27
Well, Inspector report leaks with every D program I've seen. I believe there is something in _Dmain
In lack of conformed Dplug bug, I would prefer to close this as I don't have a reproducible issue?

**Comment by aferust** [comment] 2021-11-10 10:36
Interesting. Go close it.

>> Inspector report leaks with every D program I've seen. I believe there is something in _Dmain

I will keep that in my mind.

**Comment by p0nce** [comment] 2021-11-10 11:30
It's true small leaks aren't given a high priority in Dplug (vs enterprise software), since a small leak in a plugin instance usually has no impact for the user. 

The following D program that prints its arguments:
```
import std.stdio;

void main(string[] args)
{
	foreach(s; args)
		writefln("%s", s);
}
```

has this report in Inspector
![image](https://user-images.githubusercontent.com/1067485/141104706-cc18b92b-5792-428a-b943-6707eb2a126b.png)


When built with LDC instead of DMD:
![image](https://user-images.githubusercontent.com/1067485/141104879-fe36d4d2-dad0-4521-a0fa-4d38cd61d8c7.png)

LDC but with Dr memory:
[dr-report-ldc.txt](https://github.com/AuburnSounds/Dplug/files/7512267/dr-report-ldc.txt)



For your example and that example + DMD, DrMemory crash...


so not sure what to do with all those reports. Some of the stack traces are inside MS CRT.

**Closed by p0nce** 2021-11-10 11:30 UTC
Labels: Unconfirmed

**Comment by aferust** [comment] 2021-11-10 11:35
Upon our conversation here, I also installed Inspector. I found out that it is very versatile, easy-to-use, and lightweight. I immediately delete drmemory from my windows machine forever 😁.

Merci Monsieur.

**Comment by p0nce** [comment] 2021-11-10 11:48
Yes it is free to use since a few years, you also get Inspector (though I usually prefer the AMD profiler) :)
