### ISSUE TITLE
onAnimate() on Linux has a different time scale from other platforms.

### ISSUE THREAD

**Issue by PolyVector** [AuburnSounds/Dplug#696] opened 2022-09-13 17:19 UTC
It appears onAnimate() calls are receiving time and delta in _Milliseconds_ on Linux, where Mac/Windows are in _Seconds_.  This seems to stem from x11window.d using US * 0.001, whereas other platforms using MS * 0.001.

**Comment by p0nce** [comment] 2022-09-13 17:21
Dupe of  #686 or bad fix?

**Comment by PolyVector** [comment] 2022-09-13 17:23
Sorry, probably a duplicate.  I had a list of minor bugs on my TODO to report that probably predated that report. I'll double check right now though.

**Comment by PolyVector** [comment] 2022-09-13 17:29
Yeah, It's already fixed, sorry about that! :facepalm:

**Comment by p0nce** [comment] 2022-09-13 17:29
No problem! Keep the report coming :)

**Closed by p0nce** 2022-09-13 17:29 UTC
